name: load-docker-images-from-artifacts
description: Load Docker Images from artifacts into k3d

runs:
  using: "composite"
  steps:
  - name: Make temp dir
    id: artifact_temp_dir
    shell: bash
    run: |
      path="/tmp/load-docker-images-from-artifacts"
      mkdir -p "$path"
      echo "path=${path}" >> $GITHUB_OUTPUT

  # should download emissary.tar, kat-client.tar, kat-server.tar
  - name: Download artifacts
    id: artifact_download
    uses: actions/download-artifact@v4
    with:
      path: ${{ steps.artifact_temp_dir.outputs.path }}

  - name: Extract checksum archive
    shell: bash
    run: |
      set -eou pipefail
      unzip ${{ steps.artifact_temp_dir.outputs.path }}/build-images-checksums-and-tags.zip/build-images-checksums-and-tags.zip -d ${{ github.workspace }}/docker
      ls -alh ${{ github.workspace }}/docker

  - name: Import tarballs into k3d
    shell: bash
    run: |
      images=("emissary" "kat-client" "kat-server" "test-auth" "test-shadow" "test-stats")
      for image in "${images[@]}"
      do
        echo "Importing ${image}.tar into k3d cluster"
        ./tools/bin/k3d image import "${{ steps.artifact_temp_dir.outputs.path }}/${image}.tar/${image}.tar"
      done
