name: Build images

on: [workflow_call]

env:
  VERSION: v0.0.0-build-images
  CHART_VERSION: v0.0.0-build-images

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Deps
        uses: ./.github/actions/setup-deps

      - name: Build Docker Images and save tarballs
        shell: bash
        env:
          SKIP_PUSH: "true"
        run: |
          set -eou pipefail
          make save-dev
          make save-pytest-images

      - name: Upload emissary docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: emissary.tar
          path: emissary.tar

      - name: Upload kat-client docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: kat-client.tar
          path: kat-client.tar

      - name: Upload kat-server docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: kat-server.tar
          path: kat-server.tar

      - name: Upload test-auth docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: test-auth.tar
          path: test-auth.tar

      - name: Upload test-shadow docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: test-shadow.tar
          path: test-shadow.tar

      - name: Upload test-stats docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: test-stats.tar
          path: test-stats.tar

      - name: Save image checksums/tags
        id: image-checksum
        shell: bash
        run: |
          mkdir -p /tmp/image-checksums-and-tags
          images=("emissary" "kat-client" "kat-server" "test-auth" "test-shadow" "test-stats")
          for image in "${images[@]}"
          do
            cp "docker/${image}.docker" "/tmp/image-checksums-and-tags/${image}.docker"
            cp "docker/${image}.docker.tag.local" "/tmp/image-checksums-and-tags/${image}.docker.tag.local"
          done
          (cd /tmp/image-checksums-and-tags && zip build-images-checksums-and-tags.zip *.docker *.docker.tag.local)
          echo "archive_path=/tmp/image-checksums-and-tags/build-images-checksums-and-tags.zip" >> $GITHUB_OUTPUT

      - name: Upload archive containing image checksums and tags
        uses: actions/upload-artifact@v4
        with:
          name: build-images-checksums-and-tags.zip
          path: ${{ steps.image-checksum.outputs.archive_path }}
